##  Julia　多次元配列操作



In [1]:
[1]

1-element Array{Int64,1}:
 1

In [2]:
[1, 3, 4]

3-element Array{Int64,1}:
 1
 3
 4

In [4]:
Float64[1, 3, 4]

3-element Array{Float64,1}:
 1.0
 3.0
 4.0

In [5]:
Vector(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [6]:
Vector(1:2:5)

3-element Array{Int64,1}:
 1
 3
 5

In [7]:
Array(1:2:5)

3-element Array{Int64,1}:
 1
 3
 5

In [8]:
[1:2:5;]

3-element Array{Int64,1}:
 1
 3
 5

In [9]:
collect(1:2:5)

3-element Array{Int64,1}:
 1
 3
 5

In [10]:
[i for i in 1:2:5]

3-element Array{Int64,1}:
 1
 3
 5

In [11]:
[1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [12]:
[]

Any[]

In [13]:
[
    1 2
]

1×2 Array{Int64,2}:
 1  2

In [14]:
[
    1 2
    3 4
]

2×2 Array{Int64,2}:
 1  2
 3  4

In [15]:
using LinearAlgebra

In [16]:
Matrix(1.0I, 3, 3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [17]:
Matrix{Int32}(1I, (3, 3))

3×3 Array{Int32,2}:
 1  0  0
 0  1  0
 0  0  1

In [18]:
Array(1I, (3, 3))

3×3 Array{Int64,2}:
 1  0  0
 0  1  0
 0  0  1

In [19]:
collect(1I(3))

3×3 Array{Int64,2}:
 1  0  0
 0  1  0
 0  0  1

In [20]:
a = rand(3, 3); one(a)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [21]:
b = rand(Int32, 2, 2); oneunit(b)

2×2 Array{Int32,2}:
 1  0
 0  1

In [22]:
a = Vector(1:3)

3-element Array{Int64,1}:
 1
 2
 3

In [23]:
zeros(1)

1-element Array{Float64,1}:
 0.0

In [24]:
zeros(2, 2)

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

In [25]:
a = rand(2, 2)

2×2 Array{Float64,2}:
 0.503198  0.0942551
 0.75924   0.121827

In [26]:
zero(a)

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

In [27]:
a = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [28]:
A = [1.5 2 -4; 3 -1 -6; -10 2.3 4]

3×3 Array{Float64,2}:
   1.5   2.0  -4.0
   3.0  -1.0  -6.0
 -10.0   2.3   4.0

In [29]:
factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
  1.0    0.0       0.0
 -0.15   1.0       0.0
 -0.3   -0.132196  1.0
U factor:
3×3 Array{Float64,2}:
 -10.0  2.3     4.0
   0.0  2.345  -3.4
   0.0  0.0    -5.24947

In [30]:
tr(A) # トレース

4.5

In [31]:
det(A)　# determinant

123.10000000000001

In [32]:
inv(A)

3×3 Array{Float64,2}:
  0.0796101  -0.139724  -0.129976
  0.389927   -0.276198  -0.0243704
 -0.0251828  -0.190496  -0.0609261

In [34]:
x = [1,2,3]
y = [3,1,2]
x .+ y

3-element Array{Int64,1}:
 4
 3
 5

In [36]:
x .* y

3-element Array{Int64,1}:
 3
 2
 6

In [37]:
A = [ 1 2; 3 4]
x = [1, 2]

A .+ x

2×2 Array{Int64,2}:
 2  3
 5  6

In [38]:
A .+ x'

2×2 Array{Int64,2}:
 2  4
 4  6

In [39]:
function sigmoid(x)
    1.0 ./ (1.0 .+ exp(-x))
end

sigmoid (generic function with 1 method)

In [45]:
import Pkg; Pkg.add("Gadfly")

  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
┌ Info: Precompiling Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004]
└ @ Base loading.jl:1278


LoadError: UndefVarError: linspace not defined

In [47]:
using Gadfly

x = linspace(-5.0, 5.0)
y = sigmoid(x)
plot(x=x, y=y, Geom.line)

LoadError: UndefVarError: linspace not defined